tasks:
  - init: yarn install && rustup target add wasm32-unknown-unknown && export PATH="/workspace/plantary/node_modules/near-cli/bin/":$PATH
    command: yarn run build && yarn test && near login && near dev-deploy out/plantary_nft.wasm 